#pragma once

#include <Arduino.h>

static const char REPETITIVE_MOTION_WEB_PAGE[] PROGMEM = R"HTML(
<!doctype html>
<html lang="pt-BR">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#0b1114">
<title>Motion Unit</title>
<style>
:root{--bg:#0b1114;--panel:#11191d;--line:#344047;--muted:#8e999f;--text:#e9edf0;--cyan:#29b9e8;--green:#39bf51;--red:#e43131;--field:#0c1215}
*{box-sizing:border-box}html{background:var(--bg);color:var(--text);font-family:"Arial Narrow","Roboto Condensed",Arial,sans-serif}body{margin:0;min-height:100vh;background:var(--bg)}
.brand{padding:11px 18px;border-bottom:1px solid var(--line);color:var(--cyan);font:800 15px/1.2 monospace;letter-spacing:1px;text-align:center;text-transform:uppercase}
.top{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:16px 18px;border-bottom:1px solid var(--line);font:700 13px/1.2 monospace;letter-spacing:1.5px;text-transform:uppercase}.online{color:var(--green)}.online:before{content:"";display:inline-block;width:10px;height:10px;margin-right:8px;border-radius:50%;background:currentColor}.ota{color:var(--cyan)}
main{max-width:760px;margin:auto}.instrument{position:relative;padding:24px 20px 18px;text-align:center;border-bottom:1px solid var(--line)}canvas{display:block;width:100%;max-width:700px;height:auto;margin:0 auto}.phase,.angle,.angle-label{position:absolute;left:50%;transform:translateX(-50%);width:calc(100% - 40px);text-align:center}.phase{bottom:112px;margin:0;color:var(--muted);font:700 13px monospace;letter-spacing:1.5px;text-transform:uppercase}.phase strong{display:block;margin-top:7px;color:var(--cyan);font-size:19px}.angle{bottom:42px;margin:0;color:var(--cyan);font:700 48px/1.05 monospace;word-break:break-word}.angle.status{font-size:24px;line-height:1.2;letter-spacing:1px}.angle-label{bottom:18px;color:var(--muted);font:12px monospace;letter-spacing:1px}
.controls{display:grid;grid-template-columns:1fr 1fr;padding:18px 20px 24px;border-bottom:1px solid var(--line)}button{min-height:72px;border:0;border-radius:4px;font:900 25px/1 monospace;letter-spacing:1px;cursor:pointer}.run{background:var(--green);color:#07130a}.stop{background:var(--red);color:#170505}.run:disabled,.stop:disabled{filter:saturate(.2);opacity:.45;cursor:default}
section{padding:18px 20px;border-bottom:1px solid var(--line)}h2{margin:0 0 15px;padding-bottom:10px;border-bottom:1px solid var(--line);color:#aab2b6;font:700 14px monospace;letter-spacing:2px;text-transform:uppercase}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px 28px}.field label{display:block;margin:0 0 8px;color:#abb4b8;font:700 13px monospace;letter-spacing:1px;text-transform:uppercase}.input{display:grid;grid-template-columns:1fr auto;border:1px solid #7b858a;border-radius:4px;background:var(--field)}input{min-width:0;width:100%;height:55px;padding:0 13px;border:0;outline:0;background:transparent;color:var(--cyan);font:700 25px monospace}input:focus{box-shadow:inset 0 0 0 2px var(--cyan)}.unit{min-width:58px;padding:18px 10px;border-left:1px solid #59636a;color:#d4d9db;font:700 14px monospace;text-align:center}.hint{margin-top:7px;color:#727e84;font:11px monospace}
.adjust{width:100%;min-height:42px;margin-top:10px;border:1px solid var(--cyan);background:transparent;color:var(--cyan);font-size:13px}.adjust:disabled{border-color:#586268;color:#586268;opacity:.6}.save-wrap{padding:18px 20px 28px}.save{width:100%;min-height:62px;background:var(--cyan);color:#061116}.settings-link{display:block;margin-top:17px;color:var(--cyan);font:700 13px monospace;letter-spacing:1px;text-align:center;text-decoration:none}.message{min-height:24px;margin-top:13px;color:var(--green);font:13px monospace;text-align:center}.message.error{color:#ff6565}
.step{margin:0 0 14px;padding:14px;border:1px solid var(--line);border-radius:4px;background:#0d1518}.step-title{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px;color:var(--cyan);font:700 13px monospace;letter-spacing:1px}.step-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.step-actions{display:flex;gap:7px}.step-actions button,.add-step{min-height:34px;padding:0 11px;border:1px solid var(--cyan);background:transparent;color:var(--cyan);font:700 12px monospace}.step-actions button:disabled,.add-step:disabled{opacity:.35}.step select{width:100%;height:55px;padding:0 10px;border:1px solid #7b858a;border-radius:4px;background:var(--field);color:var(--cyan);font:700 15px monospace}.add-step{width:100%;margin-top:4px}
@media(max-width:520px){.brand{font-size:12px;padding:10px 12px}.top{font-size:11px;padding:14px 12px}.instrument{padding-inline:10px}.phase,.angle,.angle-label{width:calc(100% - 20px)}.phase{bottom:92px}.angle{bottom:34px;font-size:42px}.angle.status{font-size:19px}.angle-label{bottom:14px}.controls,section,.save-wrap{padding-left:14px;padding-right:14px}.grid{gap:18px 12px}button{font-size:22px}.unit{min-width:48px;padding-inline:7px}input{font-size:22px;padding-inline:9px}}
</style>
</head>
<body>
<div class="brand">Jabur Consulting +5511-98155-0110</div>
<header class="top"><span id="unitLabel">MOTION UNIT --</span><span class="online">Wi-Fi conectado</span><span class="ota" id="ota">OTA/AP: IDLE</span></header>
<main>
  <div class="instrument">
    <canvas id="gauge" width="720" height="420" aria-label="Indicador angular"></canvas>
    <div class="phase">Fase atual<strong id="phase">CARREGANDO</strong></div>
    <div class="angle" id="angle">---.-°</div><div class="angle-label">POSIÇÃO ATUAL</div>
  </div>
  <div class="controls"><button class="run" id="run">RUN</button><button class="stop" id="stop">STOP</button></div>
  <section><h2>Movimento avulso</h2><form id="manualMove"><div class="grid">
    <div class="field"><label for="manualTarget">Posição de destino</label><div class="input"><input id="manualTarget" name="target" type="number" min="0" max="359.99" step="0.1" required><span class="unit">°</span></div><div class="hint">Sempre pelo caminho mais curto</div></div>
    <div class="field"><label for="manualRpm">Velocidade</label><div class="input"><input id="manualRpm" name="rpm" type="number" min="0.1" step="0.01" value="1.00" required><span class="unit">RPM</span></div></div>
  </div><button class="adjust" id="manualGo" type="submit">MOVER PARA A POSIÇÃO</button></form></section>
  <form id="sequenceForm"><section><h2>Passo 0 — inicialização</h2><div id="startupStep"></div></section>
    <section><h2>Sequência cíclica</h2><div id="loopSteps"></div><button class="add-step" id="addStep" type="button">+ ACRESCENTAR PASSO</button><div class="hint">De 1 a 16 passos; após o último, retorna ao passo 1.</div></section>
    <div class="save-wrap"><button class="save" id="saveSequence" type="submit">SALVAR SEQUÊNCIA</button><div class="message" id="message"></div><a class="settings-link" href="/settings">AJUSTES AVANÇADOS</a></div>
  </form>
</main>
<script>
const $=id=>document.getElementById(id);let last={angle:0,target:null},sequenceCanEdit=false,maxRpm=1,steps=[],startupStep={target:0,rpm:1,dwell:0,direction:'shortest'};
function drawGauge(){const c=$('gauge'),x=c.getContext('2d'),w=c.width,h=c.height,cx=w/2,cy=h-18,r=Math.min(w*.43,h*.92);x.clearRect(0,0,w,h);x.lineCap='butt';for(let i=0;i<=24;i++){let a=Math.PI+(Math.PI*i/24),major=i%4===0,r0=r-(major?18:8);x.beginPath();x.moveTo(cx+Math.cos(a)*r0,cy+Math.sin(a)*r0);x.lineTo(cx+Math.cos(a)*r,cy+Math.sin(a)*r);x.strokeStyle=major?'#e9edf0':'#849096';x.lineWidth=major?3:2;x.stroke()}x.beginPath();x.arc(cx,cy,r-25,Math.PI,2*Math.PI);x.strokeStyle='#59656b';x.lineWidth=2;x.stroke();x.fillStyle='#cfd5d8';x.font='20px monospace';x.textAlign='center';for(let d=0;d<=360;d+=60){let a=Math.PI+Math.PI*d/360,rr=r+28;x.fillText(d,cx+Math.cos(a)*rr,cy+Math.sin(a)*rr+7)}function mark(deg,color){let a=Math.PI+Math.PI*(deg/360),rr=r-25;x.beginPath();x.moveTo(cx+Math.cos(a)*(rr-13),cy+Math.sin(a)*(rr-13));x.lineTo(cx+Math.cos(a)*(rr+8),cy+Math.sin(a)*(rr+8));x.strokeStyle=color;x.lineWidth=6;x.stroke()}if(Number.isFinite(last.target))mark(last.target,'#29b9e8');mark(last.angle,'#e9edf0')}
async function api(path,body){let o={method:body?'POST':'GET'};if(body){o.headers={'Content-Type':'application/x-www-form-urlencoded'};o.body=new URLSearchParams(body)}let r=await fetch(path,o),j=await r.json();if(!r.ok)throw Error(j.error||'Falha na operação');return j}
let messageTimer;
function setMessage(text,error=false){clearTimeout(messageTimer);const el=$('message');el.textContent=text;el.className='message'+(error?' error':'');if(text)messageTimer=setTimeout(()=>{el.textContent='';el.className='message'},5000)}
function render(s){const unit=String(s.unit).padStart(2,'0'),phases={STOPPED:'EM REPOUSO',MOVING:'MOVENDO — PASSO '+s.step,DWELLING:'AGUARDANDO — PASSO '+s.step};$('unitLabel').textContent='MOTION UNIT '+unit;document.title='Motion Unit '+unit;last.angle=s.angle||0;last.target=null;if(s.running&&(s.phase==='MOVING'||s.phase==='DWELLING')){if(s.step===0)last.target=startupStep.target;else if(s.step>=1&&s.step<=steps.length)last.target=steps[s.step-1].target}else if(s.moveActive&&!s.running){const manualTarget=Number($('manualTarget').value);if(Number.isFinite(manualTarget)&&manualTarget>=0&&manualTarget<360)last.target=manualTarget;}$('phase').textContent=s.stall?'FALHA: MOTOR TRAVADO':(s.moveActive&&!s.running?'MOVIMENTO AVULSO':(phases[s.phase]||s.phase));const sensorText=s.sensor?s.angle.toFixed(1)+'°':(s.sensorState==='LOST'?'RECONECTANDO SENSOR':(s.sensorState==='DETECTING'?'DETECTANDO SENSOR':'LEITURA INDISPONIVEL'));$('angle').textContent=sensorText;$('angle').className=s.sensor?'angle':'angle status';$('run').disabled=s.running||s.moveActive||s.otaBusy||!s.sensor;$('stop').disabled=!s.running&&!s.moveActive;const canAdjust=!s.running&&!s.moveActive&&!s.otaBusy&&s.sensor;$('manualGo').disabled=!canAdjust;$('manualTarget').disabled=!canAdjust;$('manualRpm').disabled=!canAdjust;$('manualRpm').max=s.maxRpm;$('ota').textContent=s.otaBusy?'OTA/AP: UPDATE':'OTA/AP: IDLE';setSequenceDisabled(s.running||s.moveActive||s.otaBusy||!s.sensor);drawGauge()}
function stepHtml(step,index,startup=false){const title=startup?'PASSO 0 — FORA DO LOOP':'PASSO '+index,buttons=startup?'':`<span class="step-actions"><button type="button" data-action="up">↑</button><button type="button" data-action="down">↓</button><button type="button" data-action="delete">EXCLUIR</button></span>`;return `<div class="step" data-index="${index}"><div class="step-title"><span>${title}</span>${buttons}</div><div class="step-grid"><div class="field"><label>Posição</label><div class="input"><input data-field="target" type="number" min="0" max="359.99" step="0.1" value="${step.target.toFixed(1)}" required><span class="unit">°</span></div></div><div class="field"><label>RPM</label><div class="input"><input data-field="rpm" type="number" min="0.1" max="${maxRpm}" step="0.01" value="${step.rpm.toFixed(2)}" required><span class="unit">RPM</span></div></div><div class="field"><label>Intervalo após chegada</label><div class="input"><input data-field="dwell" type="number" min="0" max="3600000" step="1" value="${step.dwell}" required><span class="unit">ms</span></div></div><div class="field"><label>Sentido</label><select data-field="direction"><option value="shortest" ${step.direction==='shortest'?'selected':''}>MAIS CURTO</option><option value="cw" ${step.direction==='cw'?'selected':''}>HORÁRIO (CW)</option><option value="ccw" ${step.direction==='ccw'?'selected':''}>ANTI-HORÁRIO (CCW)</option></select></div></div></div>`}
function renderSequence(data){maxRpm=data.maxRpm;startupStep=data.startup;steps=data.steps;$('startupStep').innerHTML=stepHtml(data.startup,0,true);$('loopSteps').innerHTML=steps.map((s,i)=>stepHtml(s,i+1)).join('');sequenceCanEdit=data.canEdit;setSequenceDisabled(!data.canEdit)}
function setSequenceDisabled(disabled){sequenceCanEdit=!disabled;document.querySelectorAll('#sequenceForm input,#sequenceForm select,#sequenceForm button').forEach(el=>el.disabled=disabled);if(!disabled)$('addStep').disabled=steps.length>=16}
function readStep(card){return{target:Number(card.querySelector('[data-field=target]').value),rpm:Number(card.querySelector('[data-field=rpm]').value),dwell:Number(card.querySelector('[data-field=dwell]').value),direction:card.querySelector('[data-field=direction]').value}}
function collectSequence(){const startup=readStep($('startupStep').querySelector('.step')),loop=[...$('loopSteps').querySelectorAll('.step')].map(readStep),body={count:String(loop.length)};[startup,...loop].forEach((s,i)=>{body[`s${i}_target`]=s.target;body[`s${i}_rpm`]=s.rpm;body[`s${i}_dwell`]=s.dwell;body[`s${i}_direction`]=s.direction});return body}
async function loadSequence(){try{renderSequence(await api('/api/sequence'))}catch(e){setMessage(e.message,true)}}
async function refresh(){try{render(await api('/api/status'))}catch(e){setMessage('Sem comunicação com o controlador',true)}}
$('run').onclick=async()=>{try{render(await api('/api/run',{running:'1'}));setMessage('Passo inicial iniciado')}catch(e){setMessage(e.message,true)}};
$('stop').onclick=async()=>{try{render(await api('/api/run',{running:'0'}));setMessage('Movimento parado')}catch(e){setMessage(e.message,true)}};
$('manualMove').onsubmit=async e=>{e.preventDefault();try{render(await api('/api/manual-move',{target:$('manualTarget').value,rpm:$('manualRpm').value}));setMessage('Movimento avulso iniciado pelo caminho mais curto')}catch(err){setMessage(err.message,true)}};
$('addStep').onclick=()=>{if(!sequenceCanEdit||steps.length>=16)return;steps=[...$('loopSteps').querySelectorAll('.step')].map(readStep);steps.push({target:0,rpm:1,dwell:0,direction:'shortest'});renderSequence({startup:readStep($('startupStep').querySelector('.step')),steps,maxRpm,canEdit:true})};
$('loopSteps').onclick=e=>{const action=e.target.dataset.action;if(!action||!sequenceCanEdit)return;const card=e.target.closest('.step'),i=Number(card.dataset.index)-1;steps=[...$('loopSteps').querySelectorAll('.step')].map(readStep);if(action==='delete'&&steps.length>1)steps.splice(i,1);if(action==='up'&&i>0)[steps[i-1],steps[i]]=[steps[i],steps[i-1]];if(action==='down'&&i<steps.length-1)[steps[i+1],steps[i]]=[steps[i],steps[i+1]];renderSequence({startup:readStep($('startupStep').querySelector('.step')),steps,maxRpm,canEdit:true})};
$('sequenceForm').onsubmit=async e=>{e.preventDefault();try{renderSequence(await api('/api/sequence',collectSequence()));setMessage('Sequência salva com sucesso')}catch(err){setMessage(err.message,true)}};
loadSequence();refresh();setInterval(refresh,1000);addEventListener('resize',drawGauge);
</script>
</body></html>
)HTML";
